//
//  JSError.swift
//  UIKit.js
//
//  Created by Hank Brekke on 1/21/19.
//  Copyright © 2019 Hank Brekke. All rights reserved.
//

/// Errors from the UIKitJS project, typically generated by invalid calls to `JSBridge()`
public enum JSError: Error {
    /// This function does not allow multiple invocations, which have been performed.
    case duplicateCall
}
